//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTIStockMgmt.Models
{
    using System;
    using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
    
    public partial class asset
    {
      [Key]
        public int id { get; set; }

      [Required]
        public string title { get; set; }

      [Required]
      [Range(0,int.MaxValue)]
        public int price { get; set; }

      [Required]
      [Range(0,int.MaxValue)]
        public int weight { get; set; }

      [Required]
      [Range(0,int.MaxValue)]
        public int volume { get; set; }
    }
}
