//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTIStockMgmt.Models
{
  using System;
  using System.Collections.Generic;
  using System.ComponentModel.DataAnnotations;

  public partial class assembly
  {

    public assembly(assembly copy){
        id = copy.id;
        name = copy.name;
        comment = copy.comment;
        locked = copy.locked;
        tags = copy.tags;
        parent = copy.parent;
        weight = copy.weight;
        volume = copy.volume;
        retail = copy.retail;
        wholesale = copy.wholesale;
    }

    public assembly()
    {
      locked = 0;
      wholesale = 0;
      retail = 0;
      parent = 0;
      weight = 0;
      volume = 0;
    }

    [Key]
    public int id { get; set; }

    [Required]
    public string name { get; set; }

    [DisplayFormat(ConvertEmptyStringToNull = false)]
    public string comment { get; set; }

    public int locked { get; set; }

    public int retail { get; set; }

    public int wholesale { get; set; }

    public int volume { get; set; }

    public int weight { get; set; }

    [DisplayFormat(ConvertEmptyStringToNull = false)]
    public string tags { get; set; }

    public int parent { get; set; }
  }
}
