//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTIStockMgmt.Models
{
  using System;
  using System.Collections.Generic;
  using System.ComponentModel.DataAnnotations;

  public partial class assembly_assets
  {

    public assembly_assets() { }

    public assembly_assets(int assembly_id, int asset_id, int quantity, string comment){

      this.asset_id = asset_id;
      this.assembly_id = assembly_id;
      this.quantity = quantity;
      this.comment = comment;
      
    }

    [Key]
    public int id { get; set; }

    [Required]
    public int assembly_id { get; set; }

    [Required]
    public int asset_id { get; set; }

    [Required]
    public int quantity { get; set; }

    [DisplayFormat(ConvertEmptyStringToNull = false)]
    public string comment { get; set; }
  }
}
