//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTIStockMgmt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class transaction
    {
        public int id { get; set; }
        public int active_asset_id { get; set; }
        public int location_old { get; set; }
        public int location_new { get; set; }
        public int quantity_old { get; set; }
        public int quantity_new { get; set; }
        public System.DateTime date { get; set; }
        public int user_id { get; set; }
        public string comment { get; set; }
    }
}
