//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTIStockMgmt.Models
{
  using System;
  using System.Collections.Generic;
  using System.ComponentModel.DataAnnotations;

  public partial class user
  {
    public user()
    {
      online = 0;
    }

    [Key]
    public int id { get; set; }

    [Required]
    public byte[] password { get; set; }

    [Required]
    [EmailAddress]
    public string email { get; set; }

    [Required]
    public System.DateTime joined { get; set; }

    [Required]
    public string name { get; set; }

    [Required]
    public byte[] salt { get; set; }

    public int online { get; set; }
  }
}
