//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTIStockMgmt.Models
{
    using System;
    using System.Collections.Generic;
  using System.ComponentModel.DataAnnotations;
    
    public partial class user
    {
        [Key]
        public int id { get; set; }

        [Required]
        public string username { get; set; }

        [Required]
        [MinLength(6)]
        public string password { get; set; }

        [Required]
        [EmailAddress]
        public string email { get; set; }

        public System.DateTime joined { get; set; }
    }
}
